name: Build dlgTool AJ

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore packages
        run: nuget restore dlgTool.sln

      - name: Install .NET 4.6.1 targeting pack
        run: choco install netfx-4.6.1-devpack -y

      - name: Build solution
        run: msbuild dlgTool.sln /p:Configuration=Release /p:Platform="Any CPU"
