name: Build dlgTool

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Install .NET Framework 4.6.1 Developer Pack
        run: choco install netfx-4.6.1-devpack -y

      - name: Restore NuGet packages
        run: nuget restore dlgTool.sln

      - name: Build solution
        run: msbuild dlgTool.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: dlgTool-build
          path: dlgTool/bin/Release/**
